# fly.toml app configuration file generated for curarehab on 2023-05-29T09:05:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "curarehab"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  cmd = ["start.sh"]
  entrypoint = ["sh"]
  auto_rollback = true

[env]
  DB_CLIENT = "sqlite3"
  DB_FILENAME = "/data/database/data.db"
  FLY_PRIMARY_REGION = "arn"
  PORT = "6055"
  STORAGE_LOCAL_DRIVER = "local"
  STORAGE_LOCAL_ROOT = "/data/uploads"
  STORAGE_LOCATIONS = "local"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 6055
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/server/health"
    protocol = "http"
